test: False

Training1_trials_con_con: 0
Training1_trials_inc_inc_space0: 0
Training1_trials_inc_inc_space1: 0
Training1_trials_inc_inc_space2: 0
Training1_trials_inc_inc_space3: 0
Training1_trials_neu_neu: 2

Training2_trials_con_con: 4
Training2_trials_inc_inc_space0: 4
Training2_trials_inc_inc_space1: 4
Training2_trials_inc_inc_space2: 4
Training2_trials_inc_inc_space3: 4
Training2_trials_neu_neu: 0

Training_Resp_time: 4
Training_Wait_time: 1

Number_of_blocks: 2
Experiment_trials_con_con: 80
Experiment_trials_inc_inc_space0: 80
Experiment_trials_inc_inc_space1: 80
Experiment_trials_inc_inc_space2: 80
Experiment_trials_inc_inc_space3: 80
Experiment_trials_neu_neu: 0

Experiment_Resp_time: 3
Experiment_Wait_time: 1

Jitter: 1

Fix_time: 1
Feedb: True
Feedb_time: 1

words_dist: 40
stim_size: 30

